# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 289114383bd089246d23fd5491be20119d57545048b065d2e5758b1cea4ea2b8284b8888e66a9534616d023643ca54b968c7396131a1072e210777a5e583f075

test:
  secret_key_base: 6df44a7b0bdf363cf6e3848b4035d451fe71d8adbdc301a500d7482759bd2556cb3e1f726009d548ebd1f4962495afa6d247b4e484480433c16f624caa1b1c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
